### ISSUE TITLE
"assign_props_to_array_2" raises IndexError when processing octopi data

### ISSUE THREAD

**Issue by smguo** [mehta-lab/multiSero#18]
data from: /Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_octopi/20200325AdamsPlate/Averaged/500us

A1.png
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/syuan-mingguo/python/serology-COVID19/run_array_analyzer.py", line 289, in <module>
    main(sys.argv[1:])
  File "/Users/syuan-mingguo/python/serology-COVID19/run_array_analyzer.py", line 121, in main
    workflow(inputfolder, outputfolder, debug=debug)
  File "/Users/syuan-mingguo/python/serology-COVID19/run_array_analyzer.py", line 208, in workflow
    props_array = assign_props_to_array_2(props_array, props_by_loc)
  File "/Users/syuan-mingguo/python/serology-COVID19/array_analyzer/extract/image_parser.py", line 470, in assign_props_to_array_2
    if arr[key[0], key[1]] and np.mean(value.intensity_image) > np.mean(arr[key[0], key[1]].intensity_image):
IndexError: index 7 is out of bounds for axis 1 with size 6

**Comment by bryantChhun** [comment]
With a fresh new environment using opencv 3.4.2, I was able to run this fine.  The master branch currently sets pixel size to be that for the octopi images.  Commenting OUT the PIX_SIZE line will switch back to sciReader images:
(PIX_SIZE = 0.0049 = sciReader.  PIX_SIZE = 0.00185 = octopi)


```
def build_block_array(params_, pix_size=0.0049):
    """
    builds a binary array of squares centered on the expected spot position
    The array dimensions are based on parsed .xml values from the print run
    Daheng camera: IMX226, 12 MP (4000 x 3000), 1.85 um pixel size
    SciReader camera: Camera sensor / mag => 4.9 um/pixel, 2592 x 1944 pixels = 12.701 mm x 9.525 mm.
    :param params_: dict
        param dictionary from "create_xml_dict"
    :param pix_size: float
        size of pix in mm
    :return: np.ndarray, origin
    """
    # fix the pixel size, for now, in mm
    PIX_SIZE = pix_size
    # PIX_SIZE = 0.00185
```

**Comment by bryantChhun** [comment]
This problem had to do with fiducials being hardcoded to a position that didn't exist in the array.  It was addressed
